# Generated by Django 5.2.17 on 2026-08-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_author_alter_app_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
