# Generated by Django 5.2.17 on 2026-09-22 18:06

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_product_icon_alter_review_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='icon',
            field=models.ImageField(blank=True, upload_to=main.models.product_icon_path),
        ),
    ]
