# Generated by Django 5.2.17 on 2026-10-07 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_product_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_products', to=settings.AUTH_USER_MODEL, verbose_name='В избранном у'),
        ),
    ]
